import coupon from './images/coupon.svg';
import giftCoupon from './images/gift-coupon.svg';
import moneyBag from './images/money-bag.svg';
import truck from './images/truck.svg';

export const benefits = [
  {
    pContent: 'UGC is 50% more trusted more than original content generated by the brands (Crowdtap and Millward Brown Digital).',
    text: 'UGC is more trustworthy '
  },
  {
    pContent: 'UGC is 35% more memorable than original content generated by the brands (New York Times Customer Insight Group).',
    text: 'UGC is more memorable '
  },
  {
    pContent: '4.5 times higher engagement rates than other forms of media (Olapic).',
    text: 'UGC generates higher engagement rates'
  },
  {
    pContent: 'Increase conversion rates by up to 29% (Interactive Advertising Bureau).',
    text: 'UGC increases conversion rates'
  },
  
];

export default benefits;
